# Generated by Django 2.0 on 2018-08-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        ('managers', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Campaign'),
        ),
        migrations.AddField(
            model_name='quote',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.CreatorProfile'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='niches',
            field=models.ManyToManyField(to='main_app.Niche'),
        ),
    ]
