# Generated by Django 2.0 on 2018-08-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandManagerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('goals', models.TextField()),
                ('target_audience', models.TextField()),
                ('detailed_description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('submission_deadline', models.DateField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Brand')),
                ('niches', models.ManyToManyField(to='main_app.Niche')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='managers',
            field=models.ManyToManyField(to='managers.BrandManagerProfile'),
        ),
    ]
