# Generated by Django 2.0 on 2018-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='user_images/campaings_images/'),
        ),
    ]
