# Generated by Django 2.0 on 2018-09-09 23:05

from django.db import migrations, models
import managers.models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20180910_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=managers.models.upload_path_handler),
        ),
    ]
