# Generated by Django 2.0 on 2018-09-10 15:55

from django.db import migrations, models
import managers.models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20180910_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=managers.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='brandmanagerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=managers.models.upload_path_handler),
        ),
    ]
